### ISSUE TITLE
NPM 5.1?

### ISSUE THREAD

**Issue by kachkaev** [jeff-kilbride/node-npm-alpine#1]
Hi Jeff!
I'm wondering if you'd be interested in rebuilding v8 so that it got the latest npm 5.1.0. The official repo might take days to upgrade it due to bundling node and npm versions. See https://github.com/nodejs/docker-node/issues/450.

**Comment by jeff-kilbride** [comment]
Hi Alexander,

Sure! I am rebuilding the `latest` tag, right now. Once that is done, I will verify that it picked up npm 5.1.0 and build the others. Unfortunately, the automated builds on Docker Hub are fairly slow, so it will take several hours to rebuild all the version 8 tags. It should be done later today.

**Comment by jeff-kilbride** [comment]
The `latest` tag is done and verified. The rest of the version 8 tags are now building.

**Comment by kachkaev** [comment]
Oh, it's 5.3 already :open_mouth:

**Comment by jeff-kilbride** [comment]
I am upgrading the version 8 tags, right now. NPM 5.x seems to be having a lot of issues and is not very stable, e.g.:

https://github.com/npm/npm/issues/16807

They are releasing updates fairly often and I am not going to be able to upgrade these containers for every release. Sorry. I don't use NPM anymore. I have switched all my projects to `yarn`.

**Comment by kachkaev** [comment]
Thanks Jeff. I've also been using `yarn` for some time, but am currently trying to go back to npm. There's not much difference now after a complete rewrite of npm 5. Assuming the bugs are fixed, of course :–) Your images a very helpful during the transition period!
